config/routes.rb
Rails.application.routes.draw do

  root to: 'products#index'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]
  resources :about, only: [:index]

  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end

  resources :orders, only: [:create, :show]

  post 'signup', to: 'users#create'
  get 'signup', to: 'users#new'

  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'

  post 'login', to: 'sessions#create'

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
    resources :categories, only: [:index, :new, :create]
    resources :sales, except: [:edit, :update, :show]
  end

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController

  http_basic_authenticate_with name: ENV['ADMIN_NAME'], password: ENV['ADMIN_PASS']

  def show
    @categories = Category.all
    @products = Product.all
  end
end

app/views/admin/dashboard/_category.html.erb
<ul class="list-group">
  <% @categories.each do |category| %>
    <li class="list-group-item"><%= link_to category.name, category %>
    <span class="badge"><%= category.products.count %></span>
    </li>
  <% end %>
</ul>

app/views/admin/dashboard/_product.html.erb
<ul class="list-group">
  <% @products.each do |product| %>
    <li class="list-group-item"><%= link_to product.name, product %>
    <%= link_to fa_icon('trash'), [:admin, product], class: "badge",
                method: :delete,
                data: { confirm: "Are you sure?" } %>
    </li>
  <% end %>
</ul>

app/views/admin/dashboard/show.html.erb
<section class="admin-products-index">

  <header class="page-header">
    <h1>Admin &raquo; Dashboard</h1>
  </header>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h4><%= link_to 'Categories', admin_categories_path %> &raquo; 
      <span class="badge"><%= @categories.count %></span>
      </h4>
    </div>

    <%= render 'category' %>
    
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h4><%= link_to 'Products', admin_products_path %> &raquo; 
      <span class="badge"><%= @products.count %></span>
      </h4>
    </div>

    <%= render 'product'%>
    
  </div>

</section>