config/routes.rb
Rails.application.routes.draw do

  root to: 'products#index'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]
  resources :about, only: [:index]

  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end

  resources :orders, only: [:create, :show]

  post 'signup', to: 'users#create'
  get 'signup', to: 'users#new'

  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'

  post 'login', to: 'sessions#create'

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
    resources :categories, only: [:index, :new, :create]
    resources :sales, except: [:edit, :update, :show]
  end

end

app/views/layouts/_admin_dropdown.html.erb
<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">

  <span class="text-info"><%= fa_icon 'lock', text: 'Admin' %></span>
  <span class="caret"></span>
</a>
<ul class="dropdown-menu">
  <li><%= link_to 'Dashboard', [:admin, :root] %></li>
  <li><%= link_to 'Categories',  [:admin, :categories] %></li>
  <li><%= link_to 'Products',  [:admin, :products] %></li>
  <li><%= link_to 'Sales',  [:admin, :sales] %></li>
</ul>

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
<div class="alert alert-<%=type%>">
  <% if msg.is_a? Array %>
    <ul>
      <% msg.each do |m| %>
        <li><%= m %></li>
      <% end %>
    </ul>
  <% else %>
    <%= msg %>
  <% end %>
</div>
<% end %>

app/views/layouts/_sale.html.erb
<% if active_sale? %>
  <div class="alert alert-success">
    There's an active <strong><%= sale.name %></strong> sale going on!
    <strong>Everything is <%= sale.percent_off %>% off!</strong> 
  </div>
<% end %>

app/views/layouts/_top_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Jungle</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'Home', :root %>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            Categories
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <% Category.all.each do |category| %>
              <li><%= link_to category.name, category %></li>
            <% end %>
          </ul>
        </li>
        <li>
          <%= link_to 'About Us', about_index_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
       <li class="dropdown">

          <%= render 'layouts/admin_dropdown' %>

        </li>

          <%= render 'layouts/user_dropdown' %>

        <li>
          <%= link_to cart_path do %>
            <%= fa_icon "shopping-cart" %> My Cart (<%= cart.size %>)
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_user_dropdown.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">

    <% if current_user %>
      <span class="text-success">
      <%= fa_icon 'check', text: current_user.first_name %> 
      </span>
    <% else %>
      <span class="text-danger">
        <%= fa_icon 'times', text: 'Guest' %>
      </span>
    <% end %>
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu">
    <% if current_user %>
      <li><%= link_to 'Logout', :logout %></li>
    <% else %>
      <li><%= link_to 'Signup', :signup %></li>
      <li><%= link_to 'Login', :login %></li>
    <% end %>
  </ul>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jungle</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag('logo.jpeg') %>
</head>
<body>

  <%= render 'layouts/top_nav' %>

  <main class="container">

    <%= render 'layouts/flash' %>

    <%= yield %>
  </main>

  <%= yield :end_of_body %>
</body>
</html>